package org.peg4d.vm;


public enum MachineInstruction {
	EXIT,
	JUMP,
	CALL,
	RET,
	IFSUCC,
	IFFAIL,
	NOP,
	opFailure,
	opMatchText,
	opMatchByteChar,
	opMatchCharset,
	opMatchAnyChar,
	opMatchTextNot,
	opMatchByteCharNot,
	opMatchCharsetNot,
	opMatchOptionalText,
	opMatchOptionalByteChar,
	opMatchOptionalCharset,
	opRememberPosition,
	opCommitPosition,
	opBacktrackPosition,
	opRememberSequencePosition,
	opCommitSequencePosition,
	opBackTrackSequencePosition,
	opRememberFailurePosition,
	opUpdateFailurePosition,
	opForgetFailurePosition,
	opStoreObject,
	opDropStoredObject,
	opRestoreObject,
	opRestoreObjectIfFailure,
	opRestoreNegativeObject,
	opConnectObject,
	opDisableTransCapture,
	opEnableTransCapture,
	opNewObject,
	opLeftJoinObject,
	opCommitObject,
	opRefreshStoredObject,
	opTagging,
	opValue,
	opIndent,
//
//	
//	
//	PUSH_POS,
//	POP_POS,
//	POP_POS_BACK,
//	PUSH_BUFPOS,
//	POP_BUFPOS,
//	POP_BUFPOS_BACK,
//	PUSH_FPOS,
//	POP_FPOS,
//	POP_FPOS_FORGET,
//	
//	PUSH_LEFT,
//	POP_LEFT,
//	POP_LEFT_IFFAIL,
//	POP_LEFT_NOT,
//	POP_LEFT_CONNECT,
//	TMATCH, 
//	AMATCH, 
//	UMATCH, 
//	NEW, TAG, REPLACE,
//	INDENT,
}